### ISSUE TITLE
How to split the GENIA into training/dev/test dataset?

### ISSUE THREAD

**Issue by miracle24** [berlino/nest-trans-em18#1]
Hi! I wonder how do you split GENIA into trainig/dev/test dataset? Can you  provide your processed dataset files? Besides, I see in your paper, you guys also did the experiments on the ACE04 and ACE05. Could you provide these two dataset files, as well? Thanks a lot!

**Comment by berlino** [comment]
Hi!

 For GENIA data, we actually follow the splits by the paper "nested named entity recognition". 
 Note that we cannot distribute the original ACE datasets since they require license from LDC. If you have purchased these datasets, the data splits can be found in this [link](http://www.statnlp.org/paper/joint-mention-extraction-and-classification-with-mention-hypergraphs.html).

Thanks.

**Comment by miracle24** [comment]
Thanks a lot!



jichenhui2012@sina.cn
Hui Chen
School of Software, Tsinghua University
 
From: Oneblin
Date: 2018-10-22 22:57
To: berlino/nest-trans-em18
CC: miracle24; Author
Subject: Re: [berlino/nest-trans-em18] How to split the GENIA into training/dev/test dataset? (#1)
Hi!
For GENIA data, we actually follow the splits by the paper "nested named entity recognition".
Note that we cannot distribute the original ACE datasets since they require license from LDC. If you have purchased these datasets, the data splits can be found in this link.
Thanks.
